blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:article_id>/<slug>/', views.detail, name='detail'),
    path('detail/<int:article_id>/<slug>/add_comment/', views.add_comment, name='add_comment'),
    path('category/<slug>/', views.selected_category, name='selected_category'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    # Article
    path('admin_panel/add_article/', views.add_article, name='add_article'),
    path('admin_panel/article/', views.article_for_change, name='article_for_change'),
    path('admin_panel/change_article/<int:article_id>/', views.change_article, name='change_article'),
    path('admin_panel/del_article/', views.del_article, name='del_article'),
    # Category
    path('admin_panel/add_category/', views.add_category, name='add_category'),
    path('admin_panel/category/', views.category_for_change, name='category_for_change'),
    path('admin_panel/change_category/<int:category_id>/', views.change_category, name='change_category'),
    path('admin_panel/del_category/', views.del_category, name='del_category'),
    # Comment
    path('admin_panel/del_comment/', views.del_comment, name='del_comment'),
    path('admin_panel/comment/', views.comment_for_change, name='comment_for_change'),
    path('admin_panel/comment/<int:comment_id>/', views.change_comment, name='change_comment'),
    # Change password
    path('admin_panel/change_password/', views.change_password, name='change_password'),
]

webblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('auth/', include('loginsys.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save

from django.utils.text import slugify

class Category(models.Model):
	"""
	Category model
	"""
	category_name = models.CharField(max_length=30, unique=True)
	slug = models.SlugField(unique=True)

	def __str__(self):
		return self.category_name

class Article(models.Model):
	"""
	Article model
	"""
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	category = models.ManyToManyField(Category)
	article_title = models.CharField(max_length=250)
	article_content = models.TextField()
	comments_number = models.IntegerField(default=0)
	slug = models.SlugField(unique=True)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.article_title

class Comment(models.Model):
	"""
	Comment model
	"""
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	comment_text = models.TextField()
	user_name = models.CharField(max_length=50, default='')
	user_email = models.EmailField(max_length=100)

	def __str__(self):
		return self.user_name + ': ' + self.comment_text

class HashTag(models.Model):
	""" 
	HashTag model 
	"""
	name = models.CharField(max_length=200, unique=True)
	article = models.ManyToManyField(Article)

	def __str__(self):
		return self.name


def create_slug(instance, new_slug=None):
	slug = slugify(instance.article_title)
	if new_slug is not None:
		slug = new_slug
	qs = Article.objects.filter(slug=slug).order_by('-id')
	exists = qs.exists()
	if exists:
		new_slug = '%s-%s' % (slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def pre_save_article_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

pre_save.connect(pre_save_article_receiver, sender=Article)

blog/forms.py
from django.forms import Textarea, ModelForm, ModelMultipleChoiceField, EmailField, CharField
from .models import Article, Comment, Category


class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ['user_name', 'user_email', 'comment_text']
		widgets = {
            'comment_text': Textarea(attrs={'cols': 80, 'rows': 5}),
        }

class AddArticleForm(ModelForm):
	category = ModelMultipleChoiceField(queryset=Category.objects.all())
	class Meta:
		model = Article
		fields = ['article_title', 'article_content', 'category']
		article_content = {
            'comment_text': Textarea(attrs={'cols': 80, 'rows': 5}),
        }

class AddCategoryForm(ModelForm):
	class Meta:
		model = Category
		fields = ['category_name', 'slug']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Article, Comment, Category, HashTag
from .forms import CommentForm, AddArticleForm, AddCategoryForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

def index(request):
	"""
	Main page
	"""
	articles = Article.objects.order_by('-pub_date')[:5]
	categories = Category.objects.all()
	return render(request, 'blog/index.html', {'articles': articles, 'categories': categories})

def detail(request, article_id, slug):
	"""
	Show post and comments
	"""
	username = request.user.get_username()
	if username:
		email = request.user.email
	if not username:
		username = 'AnonymousUser'
		email = 'foo@example.com'
	form = CommentForm(initial={'user_name': username, 'user_email': email}, auto_id=False)
	article = get_object_or_404(Article, id=article_id)
	comments = Comment.objects.filter(article_id=article_id)
	return render(request, 'blog/detail.html', {'article': article, 'comments': comments, 'form': form})

def selected_category(request, slug):
	"""
	Show all posts in some category
	"""
	category = get_object_or_404(Category, slug=slug)
	articles = Article.objects.filter(category__slug=slug)
	return render(request, 'blog/selected_category.html', {'articles': articles, 'slug': slug})

def add_comment(request, article_id, slug):
	article = get_object_or_404(Article, id=article_id)
	# if this is a POST request we need to process the form data
	if request.method == 'POST':
		form = CommentForm(request.POST or None)
		# check whether it's valid:
		if form.is_valid():
			# Create, but don't save the new comment instance.
			comment = form.save(commit=False)
			comment.article = article
			# Update the comment
			comment.comment_text = form.cleaned_data['comment_text']
			username = request.user.get_username()
			comment.user_name = form.cleaned_data['user_name']
			comment.user_email = form.cleaned_data['user_email']
			article.comments_number = article.comment_set.count() + 1
			# Save the new instance.
			article.save()
			comment.save()
	return HttpResponseRedirect(reverse('blog:detail', args=(article_id, article.slug)))

@login_required(login_url='loginsys:login_user')
def admin_panel(request):
	return render(request, 'blog/admin_panel.html')

# Article
@login_required(login_url='loginsys:login_user')
def add_article(request):
	# if a GET (or any other method) we'll create a blank form
	form = AddArticleForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			article = form.save(commit=False)
			username = request.user.get_username()
			categories = form.cleaned_data['category']
			article_content = form.cleaned_data['article_content']
			article.author = User.objects.get(username=username)
			article.article_title = form.cleaned_data['article_title']
			article.article_content = article_content
			article.pub_date = timezone.now()
			article.save()
			# add word to hashtag if word start with '#'
			words = form.cleaned_data['article_content'].split(' ')
			for word in words:
				if word.startswith('#'):
					hash_tag, created = HashTag.objects.get_or_create(name=word)
					hash_tag.article.add(article)

			for category in categories:
				article.category.add(category)
		return HttpResponseRedirect(reverse('blog:admin_panel'))
	return render(request, 'blog/add_article.html', {'form': form})

@login_required(login_url='loginsys:login_user')
def article_for_change(request):
	articles = Article.objects.all()
	return render(request, 'blog/article_for_change.html', {'articles': articles})

@login_required(login_url='loginsys:login_user')
def change_article(request, article_id):
	article = get_object_or_404(Article, id=article_id)
	if request.method == 'POST':
		article.article_title = request.POST['article_title']
		article.article_content = request.POST['article_content']
		article.slug = request.POST['slug']
		article.save()
		return HttpResponseRedirect(reverse('blog:admin_panel'))
	return render(request, 'blog/change_article.html', {'article': article})

@login_required(login_url='loginsys:login_user')
def del_article(request):
	if request.method == 'POST':
		article_id = request.POST['article']
		article = get_object_or_404(Article, id=article_id)
		article.delete()
		return HttpResponseRedirect(reverse('blog:del_article'))
	articles = Article.objects.all()
	return render(request, 'blog/del_article.html', {'articles': articles})

# Category
@login_required(login_url='loginsys:login_user')
def add_category(request):
	form = AddCategoryForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			category = form.save(commit=False)
			category.category_name = form.cleaned_data['category_name']
			category.slug = form.cleaned_data['slug']
			category.save()
		return HttpResponseRedirect(reverse('blog:admin_panel'))
	return render(request, 'blog/add_category.html', {'form': form})

@login_required(login_url='loginsys:login_user')
def category_for_change(request):
	categories = Category.objects.all()
	return render(request, 'blog/category_for_change.html', {'categories': categories})

@login_required(login_url='loginsys:login_user')
def change_category(request, category_id):
	category = get_object_or_404(Category, id=category_id)
	if request.method == 'POST':
		category.category_name = request.POST['category_name']
		category.slug = request.POST['slug']
		category.save()
		return HttpResponseRedirect(reverse('blog:admin_panel'))
	return render(request, 'blog/change_category.html', {'category': category})

@login_required(login_url='loginsys:login_user')
def del_category(request):
	if request.method == 'POST':
		category_id = request.POST['category']
		category = get_object_or_404(Category, id=category_id)
		category.delete()
		return HttpResponseRedirect(reverse('blog:del_category'))
	categories = Category.objects.all()
	return render(request, 'blog/del_category.html', {'categories': categories})

# Change password
@login_required(login_url='loginsys:login_user')
def change_password(request):
	user = get_object_or_404(User, username=request.user)
	form = PasswordChangeForm(request.user, request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			user = form.save()
			update_session_auth_hash(request, user)
			messages.success(request, 'Your password was successfully updated!')
			return HttpResponseRedirect(reverse('blog:admin_panel'))
		else:
			messages.error(request, 'Please correct the error below.')			
	return render(request, 'blog/change_password.html', {'form': form})

# Comment
@login_required(login_url='loginsys:login_user')
def del_comment(request):
	form = AddCategoryForm(request.POST or None)
	if request.method == 'POST':
		comment_id = request.POST['comment']
		comment = get_object_or_404(Comment, id=comment_id)
		article = Article.objects.get(comment__id=comment_id)
		comment.delete()
		
		article.comments_number = article.comment_set.count()
		article.save()
		return HttpResponseRedirect(reverse('blog:del_comment'))
	comments = Comment.objects.all()
	return render(request, 'blog/del_comment.html', {'comments': comments})

@login_required(login_url='loginsys:login_user')
def comment_for_change(request):
	comments = Comment.objects.all()
	return render(request, 'blog/comment_for_change.html', {'comments': comments})

@login_required(login_url='loginsys:login_user')
def change_comment(request, comment_id):
	comment = get_object_or_404(Comment, id=comment_id)
	if request.method == 'POST':
		comment.comment_text = request.POST['comment_text']
		comment.user_name = request.POST['user_name']
		comment.user_email = request.POST['user_email']
		comment.save()
		return HttpResponseRedirect(reverse('blog:admin_panel'))
	return render(request, 'blog/change_comment.html', {'comment': comment})

blog/templates/blog/add_article.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<form action="{% url 'blog:add_article' %}" method="post">
			{% csrf_token %}

			<h4>Add article:</h4>
			<hr>
			{% include 'blog/form_template.html' %}
			<button type="submit">
				Add
			</button>
		</form>
	</div>
{% endblock %}

blog/templates/blog/add_category.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<form action="{% url 'blog:add_category' %}" method="post">
			{% csrf_token %}

			<h4>Add category:</h4>
			<hr>
			{% include 'blog/form_template.html' %}
			<button type="submit">
				Add
			</button>
		</form>
	</div>
{% endblock %}

blog/templates/blog/admin_panel.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<h3>Posts:</h3>
		<a href="{% url 'blog:add_article' %}">Add</a>
		<a href="{% url 'blog:article_for_change' %}">Change</a>
		<a class="delete" href="{% url 'blog:del_article' %}">Delete</a>
		<hr>
		<h4>Comments:</h4>
		<a href="{% url 'blog:comment_for_change' %}">Change</a>
		<a class="delete" href="{% url 'blog:del_comment' %}">Delete</a>
		<hr>
		<h4>Category:</h4>
		<a href="{% url 'blog:add_category' %}">Add</a>
		<a href="{% url 'blog:category_for_change' %}">Change</a>
		<a class="delete" href="{% url 'blog:del_category' %}">Delete</a>
		<hr>
		<a href="{% url 'blog:change_password' %}">Change password</a>
	</div>
{% endblock %}

blog/templates/blog/article_for_change.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<form action="" method="post">
			{% csrf_token %}
			<h4>Select article to change:</h4>
			<hr>
			{% for article in articles %}
				<a href="{% url 'blog:change_article' article.id %}">{{ article.article_title }}</a><br>
			{% endfor %}
		</form>
	</div>
{% endblock %}

blog/templates/blog/category_for_change.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<form action="" method="post">
			{% csrf_token %}
			<h4>Select category to change:</h4>
			<hr>
			{% for category in categories %}
				<a href="{% url 'blog:change_category' category.id %}">{{ category.category_name }}</a><br>
			{% endfor %}
		</form>
	</div>
{% endblock %}

blog/templates/blog/change_category.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<form action="" method="post">
			{% csrf_token %}
			<h4>Change category {{ category.category_name }}:</h4>
			<hr>
			<label for="name">Category name:</label><br>
			<input type="text" name="category_name" value="{{ category.category_name }}" id="name"><br>
			<label for="slug">Slug:</label><br>
			<input type="text" name="slug" value="{{ category.slug }}" id="slug"><br>
			<button type="Change">
				Change
			</button>
		</form>
	</div>
{% endblock %}

blog/templates/blog/change_comment.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<form action="" method="post">
			{% csrf_token %}
			<h4>Change comment:</h4>
			<hr>
			<label for="user_name">Comment user_name:</label><br>
			<input type="text" name="user_name" value="{{ comment.user_name }}" id="user_name"><br>
			<label for="user_email">Comment user_email:</label><br>
			<input type="text" name="user_email" value="{{ comment.user_email }}" id="user_email"><br>
			<label for="comment_text">Comment text:</label><br>
			<textarea name="comment_text" id="comment_text">{{ comment.comment_text }}</textarea><br>
			<button type="Change">
				Change
			</button>
		</form>
	</div>
{% endblock %}

blog/templates/blog/comment_for_change.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<form action="" method="post">
			{% csrf_token %}
			<h4>Select category to change:</h4>
			<hr>
			{% for comment in comments %}
				<a href="{% url 'blog:change_comment' comment.id %}">{{ comment.comment_text }}</a><br>
			{% endfor %}
		</form>
	</div>
{% endblock %}

blog/templates/blog/del_article.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<form action="" method="post">
			{% csrf_token %}

			<h4>Delete article:</h4>
			<hr>
			{% for article in articles %}
				<input type="radio" name="article" id="article{{ forloop.counter }}" value="{{ article.id }}" />
				<label for="article{{ forloop.counter }}">{{ article.article_title }}</label><br/>

			{% endfor %}
			<button type="submit" class="btn-delete">
				Delete
			</button>
		</form>
	</div>
{% endblock %}

blog/templates/blog/del_category.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<form action="" method="post">
			{% csrf_token %}

			<h4>Delete category:</h4>
			<hr>
			{% for category in categories %}
				<input type="radio" name="category" id="category{{ forloop.counter }}" value="{{ category.id }}" />
				<label for="category{{ forloop.counter }}">{{ category.category_name }}</label><br/>

			{% endfor %}
			<button type="submit" class="btn-delete">
				Delete
			</button>
		</form>
	</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">

		<h3>{{ article.article_title }}</h3>
		<p>{{ article.article_content }}</p>
		<hr>
		<form action="{% url 'blog:add_comment' article.id article.slug %}" method="post">
			{% csrf_token %}

			<h4>Comments here:</h4>
			{% for comment in comments %}
				<p><strong>{{ comment.user_name }}: </strong><br>{{ comment.user_email }}</p>
				<p>{{ comment.comment_text }}</p>
			{% endfor %}
			<hr>
			{% include 'blog/form_template.html' %}
			<button type="submit">
				Comment
			</button>
		</form>
	</div>
{% endblock %}

blog/templates/blog/form_template.html
{% for field in form %}
	<div class="form-group1">
		<div class=""> <!-- col-sm-offset-21 col-sm-101 -->
			<span class="text-danger small">{{ field.errors }}</span>								
		</div>
		<label class=""><h4>{{ field.label_tag }}<h4></label> <!-- control-label col-sm-2 -->
		<div class="field">{{ field }}</div> <!-- col-sm-10 -->
	</div>
{% endfor %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner positioner-index">
		<div class="index">
			<h3>Recent posts:</h3>
			<hr>
			{% for article in articles %}
				<h4><a href="{% url 'blog:detail' article.id article.slug %}">{{ article.article_title }}</a></h4>
				<p>Comments: {{ article.comments_number }}</p>
				{% if article.hashtag_set.all|length > 0 %}
					<p class="tags-category">Tags:</p>
					{% for tag in article.hashtag_set.all %}
						<a href="#">
							{{ tag }}
						</a> 
					{% endfor %}
				{% endif %}
				<br>
				<p class="tags-category">Category: </p>
				{% for category in article.category.all %}
					<a class="tags-category" href="{% url 'blog:selected_category' category.slug %}">
						{{ category.category_name }}
					</a> 
				{% endfor %}
				<hr>
			{% endfor %}
		</div>
		<div class="category">
			<h4>Category</h4>
			<ul>
				{% for category in categories %}
					<li><a href="{% url 'blog:selected_category' category.slug %}">{{ category.category_name }}</a></li>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock %}

blog/templates/blog/selected_category.html
{% extends 'blog/base.html' %}

{% block body %}
	<div class="positioner">
		<div class="">
			<h3>All posts in {{ slug }} category:</h3>
			<hr>
			<ul>
				{% for article in articles %}
					<li>{{ article.article_title }}</li>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock %}