blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:article_id>/<slug>/', views.detail, name='detail'),
    path('detail/<int:article_id>/<slug>/add_comment/', views.add_comment, name='add_comment'),
    path('category/<slug>/', views.selected_category, name='selected_category'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    # Article
    path('admin_panel/add_article/', views.add_article, name='add_article'),
    path('admin_panel/article/', views.article_for_change, name='article_for_change'),
    path('admin_panel/change_article/<int:article_id>/', views.change_article, name='change_article'),
    path('admin_panel/del_article/', views.del_article, name='del_article'),
    # Category
    path('admin_panel/add_category/', views.add_category, name='add_category'),
    path('admin_panel/category/', views.category_for_change, name='category_for_change'),
    path('admin_panel/change_category/<int:category_id>/', views.change_category, name='change_category'),
    path('admin_panel/del_category/', views.del_category, name='del_category'),
    # Comment
    path('admin_panel/del_comment/', views.del_comment, name='del_comment'),
    path('admin_panel/comment/', views.comment_for_change, name='comment_for_change'),
    path('admin_panel/comment/<int:comment_id>/', views.change_comment, name='change_comment'),
    # Change password
    path('admin_panel/change_password/', views.change_password, name='change_password'),
]

loginsys/urls.py
from django.urls import path, include
from . import views

app_name = 'loginsys'
urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('register/', views.register, name='register'),
]

webblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('auth/', include('loginsys.urls')),
]

loginsys/models.py
from django.db import models

# Create your models here.

loginsys/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		# class Meta it's basically information about your class
		model = User
		fields = ['username', 'email', 'password']

loginsys/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm

def login_user(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('blog:index') # page after login

			return render(request, 'loginsys/login_user.html', {
				'error_message': 'Your account has been disabled'
				})
		else:
			return render(request, 'loginsys/login.html', {
				'error_message': 'Invalid login or password'
				})
	return render(request, 'loginsys/login.html')

def logout_user(request):
	logout(request)
	return redirect('loginsys:login_user')

def register(request):
	form = UserForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		email = form.cleaned_data['email']
		user.set_password(password)
		user.save()
		user = authenticate(username=username, password=password)
		if user.is_active:
			login(request, user)
			return redirect('blog:index')
		return render(request, 'loginsys/login_user.html', {
				'error_message': 'Your account has been disabled'
				})
	return render(request, 'loginsys/register.html', {'form': form})

loginsys/templates/loginsys/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>								
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

loginsys/templates/loginsys/login.html
{% extends 'blog/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}
<div class="positioner">
	<div class="form">
		<form action="" method="post">
			{% csrf_token %}
			<label for="id_username">
				Username:
			</label><br>
			<input id="id_username" maxlength="50" name="username" type="text"><br>
			<label for="id_password">
				Password:
			</label><br>
			<input id="id_password" maxlength="50" name="password" type="password"><br>
			<button type="submit">Login</button>
			<a href="{% url 'loginsys:register' %}">Registration</a>
		</form>
	</div>
</div>
{% endblock %}

loginsys/templates/loginsys/register.html
{% extends 'blog/base.html' %}
{% block title %}Registration{% endblock %}

{% block body %}
<div class="positioner">
	<div class="form">
		<h3>Registration</h3>
		{% if error_message %}
			<p><strong>{{ error_message }}</strong></p>
		{% endif %}
		<form action="" method="post">
			{% csrf_token %}
			{% include 'loginsys/form_template.html' %}
			<button type="submit">Registration</button>
		</form>
	</div>
</div>
{% endblock %}